# https://cloud.google.com/appengine/docs/standard/python3/runtime#python-3.8
runtime: python38
instance_class: F1

# It is not neccesary because search for main.py in root with object app 
# entrypoint: gunicorn -b:$PORT src.main:app 
# No incluyas gunicorn en requirements.txt, a menos que especifiques el entrypoint

env_variables:
  FALKEN_VERSION: "1.0.0"
  ENV_PRO: "Y"
  LEVEL_LOG: "INFO, WARNING, ERROR"

  # Weather Underground API key
  API_KEY_WUNDERGROUND: "6e0b488d6bd148be8b488d6bd1d8be99"
  STATION_ID: "ICERCE9"

  # Weather EcoWitt API key
  API_KEY_ECOWITT: "cc9624af-7a05-432c-901d-e1ab0adae787"
  APPLICATION_KEY: "07FFE4105A146CF4DF0C8BD0288F1AC2"
  STATION_MAC: "BC:FF:4D:10:E4:C5"
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto